---
title: "Annual Nominal Fish Catches-googleVis Motion Charts "
author: "OmaymaS"
date: "June 21, 2016"
output: 
  html_document: 
    toc: yes
---
# Overview

## Importing and Cleaning Data
```{r warning=F,message=F}
#loading libraries
library(dplyr)
library(reshape2)
library(googleVis)
op<-options(gvis.plot.tag = "chart")
```
```{r}
#read data
dat<-read.csv("../data/fish_catches.csv",header = T,stringsAsFactors = F)
country_codes<-read.csv("../data/country_codes.csv",header = T,stringsAsFactors = F)

#remove NA columns
dat<-select(dat,Species:X2006)

#remove x from years 
names(dat)[5:13]<-sub('.', '', names(dat)[5:13])

#melt the data frame to long format
datm<-melt(dat,id=names(dat)[1:4],
           variable.name = "Year",
           value.name = "Quantity")

#Na.omit
datm<-na.omit(datm)

#change year from factor to numeric
datm$Year<-as.numeric(as.character(datm$Year))

#extract country and code from the country_codes dataframe
cc<-country_codes[,1:2]

#merge the main data and country codes 
datm<-left_join(datm,cc,by=c("Country"="Code"))

#rename columns 
names(datm)[names(datm)=="Country"]="Code"
names(datm)[names(datm)=="Description"]="Country"
```
Now, after melting the original dataframe and the adding the country name we have the following columns:
```{r echo=F}
head(datm)
```



## Creating gvis Charts